../../dependencies/std/async_fifo/async_fifo_pkg.sv
../../dependencies/std/async_fifo/async_fifo_reset_sync.sv
../../dependencies/std/async_fifo/async_fifo.sv
../../dependencies/std/async_handshake/async_handshake.sv
../../dependencies/std/axi_if/axi_if.sv
../../dependencies/std/axi_if/axi_pkg.sv
../../dependencies/std/binary_enc_dec/binary_decoder.sv
../../dependencies/std/binary_enc_dec/binary_encoder.sv
../../dependencies/std/coding/linear_sec_decoder.sv
../../dependencies/std/coding/linear_sec_encoder.sv
../../dependencies/std/coding/test_linear_sec.sv
../../dependencies/std/counter/counter.sv
../../dependencies/std/countones/countones.sv
../../dependencies/std/countones/onehot.sv
../../dependencies/std/delay/delay.sv
../../dependencies/std/edge_detector/edge_detector.sv
../../dependencies/std/fifo/fifo_controller.sv
../../dependencies/std/fifo/fifo.sv
../../dependencies/std/gray/gray_counter.sv
../../dependencies/std/gray/gray_decoder.sv
../../dependencies/std/gray/gray_encoder.sv
../../dependencies/std/lfsr/lfsr_galois.sv
../../dependencies/std/pkg/types.sv
../../dependencies/std/ram/ram.sv
../../dependencies/std/selector/demux.sv
../../dependencies/std/selector/mux.sv
../../dependencies/std/selector/selector_pkg.sv
../../dependencies/std/selector/test_selector.sv
../../dependencies/std/slicer/slicer_unit_fb.sv
../../dependencies/std/slicer/slicer_unit_hb.sv
../../dependencies/std/slicer/slicer.sv
../../dependencies/std/synchronizer/synchronizer_basic.sv
../../dependencies/std/synchronizer/synchronizer.sv
../../target/adat_pkg.sv
